cmake_minimum_required(VERSION 3.8)
project(x2_throttle)
if(NOT CMAKE_BUILD_TYPE)
  set(CMAKE_BUILD_TYPE Release)
endif()
find_package(ament_cmake REQUIRED)
find_package(rclcpp REQUIRED)
add_executable(x2_throttle src/x2_throttle.cpp)
ament_target_dependencies(x2_throttle rclcpp)
install(TARGETS x2_throttle DESTINATION lib/${PROJECT_NAME})
ament_package()
